apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: freshers-bootcamp-go
  annotations:
    github.com/project-slug: DebanganThakuria/freshers-bootcamp-go
spec:
  type: other
  lifecycle: unknown
  owner: capital
